In [30]:
import pandas as pd
import openpyxl
import numpy as np

## Exploratory Data Analysis

In [48]:
## Load data
players_df = pd.read_csv("data/CollegeBasketballPlayers2009-2021.csv")
drafted_df = pd.read_excel("data/DraftedPlayers2009-2021.xlsx")

c:\Users\giorg\Anaconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [49]:
drafted_df.columns = ['player_name','team','affiliation','year','round','round_pick','overall_pick']

In [50]:
p_vc = pd.DataFrame(players_df.year.value_counts()).reset_index()
p_vc.columns = ["year", "rows in players_df"]

d_vc = pd.DataFrame(drafted_df.year.value_counts()).reset_index()
d_vc.columns = ["year", "rows in drafted_df"]

s_vc = pd.DataFrame(drafted_df[drafted_df['round'] == 1].year.value_counts()).reset_index()
s_vc.columns = ["year", "rows in drafted_df - round 1"]

print(f"Columns in players_df: {players_df.shape[1]}")
print(f"Columns in drafted_df: {drafted_df.shape[1]}")

pd.merge(pd.merge(p_vc, d_vc, on='year'), s_vc, on='year')

Columns in players_df: 66
Columns in drafted_df: 7

    year  rows in players_df  rows in drafted_df  rows in drafted_df - round 1
0   2021                4970                  60                            30
1   2017                4743                  60                            30
2   2019                4740                  60                            30
3   2020                4733                  60                            30
4   2015                4724                  60                            30
5   2014                4722                  60                            30
6   2018                4703                  60                            30
7   2010                4698                  60                            30
8   2016                4697                  60                            30
9   2013                4608                  60                            30
10  2009                4589                  60                            30
11  2012                4586                  60                            30
12  2011                4548                  60                            30

### CollegeBasketballPlayers

Courtesy of ChatGPT:

| Column Name | Description |
|-------------|-------------|
| player_name | The name of the basketball player. |
| team        | The college basketball team that the player was part of. |
| conf        | The conference that the team belongs to. |
| GP           | Games Played - The total number of games the player participated in during the season. |
| Min_per      | Minutes Per Game - The average number of minutes the player was on the court per game. |
| Ortg         | Offensive Rating - A measure of a player's efficiency in scoring points per 100 possessions. |
| usg          | Usage Rate - The percentage of team plays used by a player while on the court. |
| eFG          | Effective Field Goal Percentage - A statistic that adjusts field goal percentage to account for the fact that three-point shots are worth more than two-point shots. |
| TS_per       | True Shooting Percentage - A measure of shooting efficiency that takes into account field goals, three-point field goals, and free throws. |
| ORB_per      | Offensive Rebound Percentage - The percentage of available offensive rebounds a player grabs while on the court. |
| DRB_per      | Defensive Rebound Percentage - The percentage of available defensive rebounds a player grabs while on the court. |
| TRB_per      | Total Rebound Percentage - The percentage of available total rebounds a player grabs while on the court. |
| AST_per      | Assist Percentage - The percentage of teammate field goals a player assisted while on the court. |
| STL_per      | Steal Percentage - The percentage of opponent possessions that end with a steal by the player while on the court. |
| BLK_per      | Block Percentage - The percentage of opponent two-point field goal attempts blocked by the player while on the court. |
| TOV_per      | Turnover Percentage - The percentage of player possessions that end in a turnover. |
| USG_per      | Usage Percentage - Another measure of the percentage of team plays used by a player while on the court. |
| PPR          | Pure Point Rating - A measure of a player's ability to generate points for themselves and their teammates. |
| PTS_per      | Points Per Game - The average number of points scored by the player per game. |
| 2P_per       | Two-Point Field Goals Per Game - The average number of two-point field goals made by the player per game. |
| 3P_per       | Three-Point Field Goals Per Game - The average number of three-point field goals made by the player per game. |
| FT_per       | Free Throws Per Game - The average number of free throws made by the player per game. |
| 2P%          | Two-Point Field Goal Percentage - The percentage of two-point field goal attempts made by the player. |
| 3P%          | Three-Point Field Goal Percentage - The percentage of three-point field goal attempts made by the player. |
| FT%          | Free Throw Percentage - The percentage of free throw attempts made by the player. |
| AST          | Assists - The total number of assists made by the player during the season. |
| STL          | Steals - The total number of steals made by the player during the season. |
| BLK          | Blocks - The total number of blocks made by the player during the season. |
| PTS          | Points - The total number of points scored by the player during the season. |
| oreb, dreb, treb | Offensive, defensive, and total rebounds made by the player per game. |
| dgbpm        | Defensive Box Plus-Minus - A box score estimate of the defensive points per 100 possessions a player contributed above a league-average player, translated to an average team. |

### Drafted Players dataset

In [24]:
drafted_df.columns = ['player_name','team','affiliation','year','round','round_pick','overall_pick']

first_round_drafted = drafted_df[drafted_df['round'] == 1]

In [44]:
first_round_drafted.year.value_counts()

2021.0    30
2020.0    30
2019.0    30
2018.0    30
2017.0    30
2016.0    30
2015.0    30
2014.0    30
2013.0    30
2012.0    30
2011.0    30
2010.0    30
2009.0    30
Name: year, dtype: int64

### Merged dataset

In [28]:
df = pd.merge(players_df, first_round_drafted, on=['player_name','year','team'], how='left')
df.head()

,player_name,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65,affiliation,round,round_pick,overall_pick
0,DeAndrae Ross,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,1.6,...,1.1923,0.3462,0.0385,3.8846,NaN,6.22026,NaN,NaN,NaN,NaN
1,Pooh Williams,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,3.8,...,1.8235,0.4118,0.2353,5.9412,NaN,3.94375,NaN,NaN,NaN,NaN
2,Jesus Verdejo,South Florida,BE,27,72.0,96.2,21.8,45.7,47.98,2.1,...,1.9630,0.4815,0.0000,12.1852,NaN,10.92680,NaN,NaN,NaN,NaN
3,Mike Hornbuckle,Pepperdine,WCC,30,44.5,97.7,16.0,53.6,53.69,4.1,...,1.1000,0.5667,0.1333,4.9333,NaN,6.77427,NaN,NaN,NaN,NaN
4,Anthony Brown,Pacific,BW,33,56.2,96.5,22.0,52.8,54.31,8.3,...,0.8485,0.4545,0.3333,7.5758,NaN,0.00000,NaN,NaN,NaN,NaN

In [31]:
df['first_round_picked'] = np.where(df['round'].isnull(), 0, 1)

In [35]:
df.columns

Index(['player_name', 'team', 'conf', 'GP', 'Min_per', 'Ortg', 'usg', 'eFG',
       'TS_per', 'ORB_per', 'DRB_per', 'AST_per', 'TO_per', 'FTM', 'FTA',
       'FT_per', 'twoPM', 'twoPA', 'twoP_per', 'TPM', 'TPA', 'TP_per',
       'blk_per', 'stl_per', 'ftr', 'yr', 'ht', 'num', 'porpag', 'adjoe',
       'pfr', 'year', 'pid', 'type', 'Rec Rank', 'ast/tov', 'rimmade',
       'rimmade+rimmiss', 'midmade', 'midmade+midmiss',
       'rimmade/(rimmade+rimmiss)', 'midmade/(midmade+midmiss)', 'dunksmade',
       'dunksmiss+dunksmade', 'dunksmade/(dunksmade+dunksmiss)', 'pick',
       'drtg', 'adrtg', 'dporpag', 'stops', 'bpm', 'obpm', 'dbpm', 'gbpm',
       'mp', 'ogbpm', 'dgbpm', 'oreb', 'dreb', 'treb', 'ast', 'stl', 'blk',
       'pts', 'Unnamed: 64', 'Unnamed: 65', 'affiliation', 'round',
       'round_pick', 'overall_pick', 'first_round_picked'],
      dtype='object')

**PCA**